apiVersion: v1
kind: Service
metadata:
   labels:
      app: fortune-service
      deployment: pks-workshop
   name: fortune-service
spec:
   type: LoadBalancer
   selector:
      app: fortune
   ports:
   - port: 80
     targetPort: 8080
     name: ui
---
apiVersion: v1
kind: Pod
metadata:
   labels:
      app: fortune
      deployment: pks-workshop
   name: fortune
spec:
   containers:
   - image: nlxarosa/fortune-demo-k8s:latest
     name: fortune-ui
     ports:
     - containerPort: 8080
       protocol: TCP
     env:
     - name: SPRING_REDIS_HOST
       value: "fortune-redis"
