apiVersion: v1
kind: Service
metadata:
   labels:
      app: fortune-redis
      deployment: pks-workshop
   name: fortune-redis
   annotations:
      cloud.google.com/load-balancer-type: "Internal"
spec:
   type: LoadBalancer
   selector:
      app: fortune-redis
   ports:
   - port: 6379
     name: fortune-redis
---
apiVersion: v1
kind: Pod
metadata:
   labels:
      app: fortune-redis
      deployment: pks-workshop
   name: fortune-redis
spec:
   containers:
   - image: redis
     name: fortune-redis
     ports:
     - containerPort: 6379
       protocol: TCP

